# Generated by Django 5.0.1 on 2024-01-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_rename_icon_classes_fontawesomeicon_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Your first name', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(default='Your last name', max_length=255, verbose_name='Last Name')),
                ('description', models.TextField(default='Your description', verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='profile_thumbnail/', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'About me',
                'verbose_name_plural': 'About me',
            },
        ),
        migrations.CreateModel(
            name='AboutSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('about', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutinfo', verbose_name='About me')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('url', models.URLField(verbose_name='URL')),
                ('about', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutinfo', verbose_name='About me')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.fontawesomeicon', verbose_name='Font Awesome Icon')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
    ]
