# Generated by Django 5.0.1 on 2024-01-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Your first name', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(default='Your last name', max_length=255, verbose_name='Last Name')),
                ('description', models.TextField(default='Your description', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('about', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutinfo', verbose_name='About me')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon_classes', models.CharField(max_length=255, verbose_name='Font Awesome Icon Classes')),
                ('about', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutinfo', verbose_name='About me')),
            ],
            options={
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
    ]
