# Generated by Django 5.0.1 on 2024-01-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_create_default_aboutinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinfo',
            options={'verbose_name': 'About me', 'verbose_name_plural': 'About me'},
        ),
        migrations.AlterField(
            model_name='aboutskill',
            name='display_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='display_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Display Order'),
        ),
    ]
