# Generated by Django 5.0.1 on 2024-01-23 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_create_default_aboutinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutskill',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='about.aboutinfo', verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='about.aboutinfo', verbose_name='About me'),
        ),
    ]
