# Generated by Django 5.0.1 on 2024-01-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutinfo_options_and_more'),
        ('common', '0003_rename_icon_classes_fontawesomeicon_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutskill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Social Link', 'verbose_name_plural': 'Social Links'},
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_classes',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.fontawesomeicon', verbose_name='Font Awesome Icon'),
            preserve_default=False,
        ),
    ]
