# Generated by Django 5.0.1 on 2024-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_alter_experience_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.ImageField(upload_to='experience_thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
