# Generated by Django 5.0.1 on 2024-01-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_alter_experience_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='experience_thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
