# Generated by Django 5.0.1 on 2024-01-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactthread_gdpr_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(default='default@example.com', max_length=254, verbose_name='Admin Email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
