# Generated by Django 5.0.1 on 2024-01-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_create_default_admincontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincontact',
            name='website_email',
            field=models.EmailField(default='default@example.com', max_length=254, verbose_name='Website Email'),
        ),
    ]
