# Generated by Django 5.0.1 on 2024-01-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_admincontact_website_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincontact',
            name='admin_email',
            field=models.EmailField(default='admin@example.com', max_length=254, verbose_name='Admin Email'),
        ),
        migrations.AlterField(
            model_name='admincontact',
            name='website_email',
            field=models.EmailField(default='website@example.com', max_length=254, verbose_name='Website Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='sender',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'Utilisateur')], max_length=255, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='contactthread',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse électronique'),
        ),
        migrations.AlterField(
            model_name='contactthread',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
    ]
