# Generated by Django 5.0.1 on 2024-01-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_rename_icon_classes_fontawesomeicon_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects_thumbnails/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.category', verbose_name='Category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(through='projects.ProjectCategory', to='projects.category', verbose_name='Categories'),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.fontawesomeicon', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory', verbose_name='Project Category')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.technology', verbose_name='Technology')),
            ],
            options={
                'verbose_name': 'Project Technology',
                'verbose_name_plural': 'Project Technologies',
            },
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='technologies',
            field=models.ManyToManyField(through='projects.ProjectTechnology', to='projects.technology', verbose_name='Technologies'),
        ),
    ]
