# Generated by Django 5.0.1 on 2024-01-24 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_fontawesomeicon_title_and_more'),
        ('projects', '0002_alter_category_name_alter_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_through', to='projects.project', verbose_name='Project'),
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Text')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.fontawesomeicon', verbose_name='Icon')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Link',
                'verbose_name_plural': 'Project Links',
            },
        ),
    ]
