# Generated by Django 5.0.1 on 2024-01-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectcategory_project_projectlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project', verbose_name='Project'),
        ),
    ]
