# Generated by Django 5.0.1 on 2024-01-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_paragraph_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
