# Generated by Django 5.0.1 on 2024-01-22 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_rename_icon_classes_fontawesomeicon_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.CharField(choices=[('language', 'Programming Languages & Tools'), ('framework', 'Frameworks & Libraries'), ('workflow', 'Workflow')], max_length=255, verbose_name='Category')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.fontawesomeicon', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'unique_together': {('name', 'category')},
            },
        ),
    ]
