# Generated by Django 5.0.1 on 2024-01-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('icon', models.CharField(max_length=255, verbose_name='Icon')),
                ('icon_color', models.CharField(max_length=255, verbose_name='Icon Color')),
            ],
            options={
                'verbose_name': 'Award Category',
                'verbose_name_plural': 'Award Categories',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('file', models.FileField(blank=True, null=True, upload_to='awards_files/', verbose_name='PDF File')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='awards.awardcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
            },
        ),
    ]
