# Generated by Django 5.0.1 on 2024-01-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_awardcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='obtain_date',
            field=models.DateField(blank=True, null=True, verbose_name='Obtain Date'),
        ),
    ]
