# Generated by Django 5.0.1 on 2024-01-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FontAwesomeIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('icon_classes', models.CharField(max_length=255, verbose_name='Font Awesome Icon Classes')),
            ],
        ),
    ]
