# Generated by Django 5.0.1 on 2024-01-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fontawesomeicon',
            options={'verbose_name': 'Font Awesome Icon', 'verbose_name_plural': 'Font Awesome Icons'},
        ),
    ]
