# Generated by Django 5.0.1 on 2024-01-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_fontawesomeicon_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fontawesomeicon',
            old_name='icon_classes',
            new_name='classes',
        ),
    ]
