# Generated by Django 5.0.1 on 2024-01-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_icon_classes_fontawesomeicon_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fontawesomeicon',
            old_name='classes',
            new_name='css_classes',
        ),
    ]
