# Generated by Django 5.0.1 on 2024-01-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_classes_fontawesomeicon_css_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Site Title', max_length=255, verbose_name='Site Title')),
                ('description', models.TextField(default='Default Site Description', verbose_name='Site Description')),
                ('author', models.CharField(default='Default Author', max_length=255, verbose_name='Author')),
                ('og_title', models.CharField(default='Default OG Title', max_length=255, verbose_name='OG Title')),
                ('og_description', models.TextField(default='Default OG Description', verbose_name='OG Description')),
                ('og_image', models.URLField(blank=True, null=True, verbose_name='OG Image')),
            ],
            options={
                'verbose_name': 'Site Meta Data',
                'verbose_name_plural': 'Site Meta Data',
            },
        ),
    ]
