# Generated by Django 5.0.1 on 2024-01-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_fontawesomeicon_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='favicon/', verbose_name='Image')),
                ('credits_html', models.TextField(blank=True, help_text='HTML for the credits', null=True, verbose_name='Credits HTML')),
                ('site_meta_data', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favicon', to='common.sitemetadata', verbose_name='Site Meta Data')),
            ],
            options={
                'verbose_name': 'Favicon',
                'verbose_name_plural': 'Favicons',
            },
        ),
        migrations.CreateModel(
            name='FooterCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Display Order')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('html', models.TextField(help_text='HTML for the credits', verbose_name='HTML')),
                ('site_meta_data', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='common.sitemetadata', verbose_name='Site Meta Data')),
            ],
            options={
                'verbose_name': 'Footer Credit',
                'verbose_name_plural': 'Footer Credits',
                'ordering': ['display_order'],
                'abstract': False,
            },
        ),
    ]
