# Generated by Django 5.0.1 on 2024-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='School Name')),
                ('program', models.CharField(max_length=255, verbose_name='Program')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('thumbnail', models.ImageField(upload_to='education_images/', verbose_name='Thumbnail')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
